# Default SIFT front-end configuration.

SceneOptimizer:
  _target_: gtsfm.scene_optimizer.SceneOptimizer
  save_gtsfm_data: True
  save_two_view_correspondences_viz: False
  save_3d_viz: True
  pose_angular_error_thresh: 5 # degrees

  retriever:
    _target_: gtsfm.retriever.netvlad_retriever.NetVLADRetriever
    num_matched: 20
    min_score: 0.3

  correspondence_generator:
    _target_: gtsfm.frontend.correspondence_generator.det_desc_correspondence_generator.DetDescCorrespondenceGenerator

    feature_extractor:
      _target_: gtsfm.feature_extractor.FeatureExtractor
      detector_descriptor:
        _target_: gtsfm.frontend.detector_descriptor.sift.SIFTDetectorDescriptor
        max_keypoints: 10000

    matcher:
      _target_: gtsfm.frontend.matcher.oneway_matcher.OneWayMatcher
      ratio_test_threshold: 0.8

  two_view_estimator:
    _target_: gtsfm.theia_two_view_estimator.TheiaTwoViewEstimator
    eval_threshold_px: 4 # in px

  multiview_optimizer:
    _target_: gtsfm.multi_view_optimizer.MultiViewOptimizer

    # comment out to not run
    view_graph_estimator:
      _target_: gtsfm.view_graph_estimator.cycle_consistent_rotation_estimator.CycleConsistentRotationViewGraphEstimator
      edge_error_aggregation_criterion: MEDIAN_EDGE_ERROR

    rot_avg_module:
      _target_: gtsfm.averaging.rotation.shonan.ShonanRotationAveraging

    trans_avg_module:
      _target_: gtsfm.averaging.translation.averaging_1dsfm.TranslationAveraging1DSFM
      robust_measurement_noise: True
      projection_sampling_method: SAMPLE_INPUT_MEASUREMENTS

    data_association_module:
      _target_: gtsfm.data_association.data_assoc.DataAssociation
      min_track_len: 2
      triangulation_options:
        _target_: gtsfm.data_association.point3d_initializer.TriangulationOptions
        reproj_error_threshold: 100
        mode:
          _target_: gtsfm.data_association.point3d_initializer.TriangulationSamplingMode
          value: RANSAC_SAMPLE_UNIFORM
        max_num_hypotheses: 100
      save_track_patches_viz: False

    bundle_adjustment_module:
      _target_: gtsfm.bundle.bundle_adjustment.BundleAdjustmentOptimizer
      output_reproj_error_thresh: 3 # for post-optimization filtering
      robust_measurement_noise: True
      shared_calib: False

  # comment out to not run
  dense_multiview_optimizer:
    _target_: gtsfm.densify.mvs_patchmatchnet.MVSPatchmatchNet
